FROM centos:centos7.9.2009

RUN set -ex \
        && yum install -y epel-release \
        && yum install -y gcc gcc-c++ make cmake3 \
        && yum install -y zlib* \
        && yum install -y centos-release-scl \
        && yum install -y devtoolset-7 \
        && scl enable devtoolset-7 bash 
